"""Query package — backward-compatible re-exports from domain submodules."""

from api.queries._common import (
    _build_paginated_response,
    _MONEY_SCALE,
    fetch_campaign_finance_provenance,
    fetch_entity_provenance,
    fetch_one_row,
)
from api.queries.campaign_finance import (
    CAMPAIGN_FINANCE_CANDIDATE_DETAIL_SQL,
    CAMPAIGN_FINANCE_COMMITTEE_DETAIL_SQL,
    CAMPAIGN_FINANCE_FILING_DETAIL_SQL,
    UnknownCountySlugError,
    build_zero_committee_fundraising_summary,
    build_zero_candidate_fundraising_summary,
    fetch_candidate_list,
    fetch_candidate_summary,
    fetch_candidates_by_slug,
    fetch_candidate_ie_summary,
    fetch_candidate_ie_transactions,
    fetch_cf_summary_by_county,
    fetch_committee_filing_breakdown,
    fetch_committee_fundraising_summary,
    fetch_committee_list,
    fetch_committees_by_slug,
    fetch_state_campaign_finance_detail,
    fetch_state_campaign_finance_summaries,
    fetch_persons_by_slug,
    fetch_transaction_list,
)
from api.queries.entity_resolution import (
    fetch_entity_matches,
    fetch_er_cluster_detail,
    fetch_er_cluster_list,
    fetch_er_summary,
)
from api.queries.property import (
    fetch_donors_with_property,
    fetch_parcel_detail,
    fetch_parcel_list,
)
from api.queries.civics import (
    fetch_candidacy_detail,
    fetch_contacts_by_owner,
    fetch_contest_candidacies,
    fetch_contest_detail,
    fetch_jurisdiction_exists,
    fetch_office_detail,
    fetch_office_officeholders,
    fetch_officeholding_detail,
    fetch_offices_by_jurisdiction,
)
from api.queries.search import fetch_search_results
from api.queries.metadata import fetch_data_sources_metadata, fetch_runtime_coverage_registry

__all__ = [
    "CAMPAIGN_FINANCE_CANDIDATE_DETAIL_SQL",
    "CAMPAIGN_FINANCE_COMMITTEE_DETAIL_SQL",
    "CAMPAIGN_FINANCE_FILING_DETAIL_SQL",
    "UnknownCountySlugError",
    "_MONEY_SCALE",
    "_build_paginated_response",
    "build_zero_committee_fundraising_summary",
    "build_zero_candidate_fundraising_summary",
    "fetch_candidacy_detail",
    "fetch_campaign_finance_provenance",
    "fetch_contest_candidacies",
    "fetch_contest_detail",
    "fetch_candidate_list",
    "fetch_candidate_summary",
    "fetch_candidates_by_slug",
    "fetch_candidate_ie_summary",
    "fetch_candidate_ie_transactions",
    "fetch_cf_summary_by_county",
    "fetch_committee_filing_breakdown",
    "fetch_committee_fundraising_summary",
    "fetch_committee_list",
    "fetch_committees_by_slug",
    "fetch_state_campaign_finance_detail",
    "fetch_state_campaign_finance_summaries",
    "fetch_donors_with_property",
    "fetch_entity_matches",
    "fetch_entity_provenance",
    "fetch_er_cluster_detail",
    "fetch_er_cluster_list",
    "fetch_er_summary",
    "fetch_office_detail",
    "fetch_contacts_by_owner",
    "fetch_jurisdiction_exists",
    "fetch_office_officeholders",
    "fetch_officeholding_detail",
    "fetch_offices_by_jurisdiction",
    "fetch_one_row",
    "fetch_parcel_detail",
    "fetch_parcel_list",
    "fetch_persons_by_slug",
    "fetch_data_sources_metadata",
    "fetch_runtime_coverage_registry",
    "fetch_search_results",
    "fetch_transaction_list",
]
