FROM postgres:18-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-18-postgis-3 \
        postgresql-18-postgis-3-scripts \
        postgresql-18-age && \
    rm -rf /var/lib/apt/lists/*
