
from __future__ import annotations

import argparse
import re
from datetime import UTC, date, datetime
from pathlib import Path

from core.keel_review_schedule import (
    compute_review_status,
    format_status_table,
    load_schedule,
)
from core.keel_status import (
    LayerSummary,
    StatusRow,
    collect_layer_summaries,
)

_SENTINEL = "<!-- GENERATED by make keel-current; hand edits will be overwritten. -->"

# Match `### N. Title` headings only (numbered open-questions items).
# Why "numbered only": open_questions.md uses `### R1.`/`### R2.` for the
# Resolved section and an unnumbered `###` for the Meta-question section.
# Casual mode's rollup wants the live open-questions list, not the
# resolved/meta noise — the regex `\d+\.` filters those out cleanly.
_OQ_HEADING_PATTERN = re.compile(r"^### (\d+\. .+)$", re.MULTILINE)


def _render_status_row_inline(row: StatusRow) -> str:
    parts = [f"scope={row.scope}", f"status={row.status}"]
    if row.detail is not None:
        parts.append(f"detail={row.detail}")
    if row.evidence_path is not None:
        parts.append(f"evidence={row.evidence_path.as_posix()}")
    return " ".join(parts)


def _render_layer_block(summary: LayerSummary) -> str:
    lines = [f"### {summary.layer_id} ({summary.name})"]
    lines.append(f"- status: `{summary.status}`")
    lines.append(f"- interpretation: {summary.interpretation}")
    if summary.scope_rows:
        lines.append("- scopes:")
        for row in summary.scope_rows:
            lines.append(f"  - {_render_status_row_inline(row)}")
    return "\n".join(lines)


def _render_layer_status_section(*, repo_root: Path, today_utc: date) -> str:
    summaries = collect_layer_summaries(repo_root=repo_root, today_utc=today_utc)
    blocks = ["## Layer status", ""]
    blocks.append(
        "One block per layer in `layers.yaml` declared order. "
        "See `docs/keel/layers.md` for the full failure-mode catalog."
    )
    blocks.append("")
    for summary in summaries:
        blocks.append(_render_layer_block(summary))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def _render_recurring_reviews_section(*, repo_root: Path, today_utc: date) -> str:
    # The schedule file is OPTIONAL by design: a project that hasn't
    # configured recurring reviews yet still gets a usable rollup,
    # rather than a hard crash on missing-file. Tests cover both paths.
    schedule_path = repo_root / "keel_reviews.yaml"
    if not schedule_path.is_file():
        return "## Recurring reviews\n\n(no recurring reviews configured)\n"
    schedule = load_schedule(schedule_path)
    rows = compute_review_status(repo_root=repo_root, schedule=schedule, now_date=today_utc)
    # Wrap the tab-separated table in a fenced block so markdown renderers
    # don't mangle the columns. Also cleaner for an LLM scanning the paste.
    return "## Recurring reviews\n\n```\n" + format_status_table(rows) + "\n```\n"


def _render_parking_lot_section() -> str:
    # Single hard-coded link line. Parking lot lives in checklist.md and
    # stays SSOT there. Casual mode points the LLM at the canonical file
    # rather than copying its contents.
    return (
        "## Parking lot\n\n"
        "Surfaced items that don't block current work live in the canonical "
        "`docs/keel/checklist.md` parking lot. Read it there — this rollup "
        "deliberately does not duplicate that content.\n"
    )


def _render_open_questions_section(*, repo_root: Path) -> str:
    oq_path = repo_root / "docs" / "keel" / "open_questions.md"
    lines = ["## Open questions", ""]
    lines.append(
        "Full text + resolution history in `docs/keel/open_questions.md`. "
        "Headings (numbered items only) below for at-a-glance scan:"
    )
    lines.append("")
    if oq_path.is_file():
        text = oq_path.read_text(encoding="utf-8")
        for match in _OQ_HEADING_PATTERN.finditer(text):
            lines.append(f"- {match.group(1)}")
    else:
        lines.append("- (no open_questions.md found)")
    return "\n".join(lines).rstrip() + "\n"


def _render_footer() -> str:
    return (
        "---\n\n"
        "Regenerate this file with `make keel-current`. The generation walks "
        "`layers.yaml`, `keel_reviews.yaml`, and `docs/keel/open_questions.md` "
        "and emits this rollup deterministically.\n"
    )


def render_current_md(*, repo_root: Path, today_utc: date) -> str:
    sections: list[str] = []
    sections.append(_SENTINEL)
    sections.append(f"# Keel — current state rollup ({today_utc.isoformat()} UTC)")
    sections.append("")
    sections.append("Regenerate with `make keel-current`.")
    sections.append("")
    sections.append(_render_layer_status_section(repo_root=repo_root, today_utc=today_utc))
    sections.append(_render_recurring_reviews_section(repo_root=repo_root, today_utc=today_utc))
    sections.append(_render_parking_lot_section())
    sections.append(_render_open_questions_section(repo_root=repo_root))
    sections.append(_render_footer())
    return "\n".join(sections)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate docs/keel/CURRENT.md (casual-mode rollup artifact)."
    )
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--date", help="UTC date override (YYYY-MM-DD); defaults to today UTC.")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: <repo>/docs/keel/CURRENT.md).",
    )
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    today_utc = date.fromisoformat(args.date) if args.date else datetime.now(UTC).date()
    out_path = args.out if args.out is not None else (repo_root / "docs" / "keel" / "CURRENT.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_current_md(repo_root=repo_root, today_utc=today_utc), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
