"""Tests for `core.keel_current` (the `make keel-current` writer).

Asserts structural sections + non-empty content. Exact wording is not
asserted (would be brittle); structural contract is.
"""

from __future__ import annotations

import re
from datetime import UTC, date, datetime
from pathlib import Path

import core.keel_current as keel_current


_LAYERS_YAML = """schema_version: 1
layers:
  - id: L1
    name: jurisdiction_anchors
    status: piloted
    scope: per_jurisdiction
    scope_strategy:
      type: fixed_scope
      value: NC
    triggered_by:
      - anchor_research
    required_evidence:
      schema: evidence_schemas/L1.json
    file_path_triggers:
      - docs/anchors/**
    gate_command: make gate-L1 JURISDICTION={scope}
  - id: L12
    name: session_output_summary
    status: introduced
    scope: per_session
    scope_strategy:
      type: session_summary
      field: session_id
    triggered_by:
      - session_close
    required_evidence:
      schema: evidence_schemas/L12.json
    file_path_triggers:
      - layers.yaml
    gate_command: uv run python -m core.keel_session_output
"""


_L1_SCHEMA = """{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["layer", "scope", "schema_version", "produced_at_utc",
               "repo_sha", "gate_command", "status"],
  "properties": {
    "layer": {"const": "L1"},
    "scope": {"type": "string"},
    "schema_version": {"const": 1},
    "produced_at_utc": {"type": "string", "format": "date-time"},
    "repo_sha": {"type": "string"},
    "gate_command": {"type": "string"},
    "status": {"type": "string"}
  }
}
"""


_REVIEWS_YAML = """schema_version: 1
reviews:
  - review_id: calibration_audit
    cadence: quarterly
    primary_prompt: prompts/judge/calibration_audit.md
    skeptic_prompt: prompts/judge/calibration_audit_skeptic.md
    evidence_root: evidence/review/calibration_audit
  - review_id: escalation_review
    cadence: weekly
    primary_prompt: prompts/judge/escalation_review.md
    skeptic_prompt: prompts/judge/escalation_review_skeptic.md
    evidence_root: evidence/review/escalation_review
"""


_OPEN_QUESTIONS_MD = """# Keel open questions

## Open

### 1. Evidence retention
Some body text.

### 2. Evidence commit path and publication policy — resolved 2026-04-25
Body.

### 3. Human escalation budget
Body.

## Resolved

### R1. Layer numbering and identity
Body.
"""


_CHECKLIST_MD = """# Keel checklist

## Parking lot

**KNOWN_PARKING_LOT_CANARY_LINE_xyzz** — this is a unique substring used
by tests to confirm parking-lot content is NOT duplicated into CURRENT.md.
"""


def _build_synthetic_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "layers.yaml").write_text(_LAYERS_YAML, encoding="utf-8")
    schemas = repo / "evidence_schemas"
    schemas.mkdir()
    (schemas / "L1.json").write_text(_L1_SCHEMA, encoding="utf-8")
    (schemas / "L12.json").write_text(_L1_SCHEMA, encoding="utf-8")
    (repo / "keel_reviews.yaml").write_text(_REVIEWS_YAML, encoding="utf-8")
    docs_keel = repo / "docs" / "keel"
    docs_keel.mkdir(parents=True)
    (docs_keel / "open_questions.md").write_text(_OPEN_QUESTIONS_MD, encoding="utf-8")
    (docs_keel / "checklist.md").write_text(_CHECKLIST_MD, encoding="utf-8")
    return repo


def test_render_current_md_starts_with_sentinel(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    first_line = out.splitlines()[0]
    assert first_line == "<!-- GENERATED by make keel-current; hand edits will be overwritten. -->"


def test_render_current_md_contains_today_date(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    head = "\n".join(out.splitlines()[:3])
    assert "2026-04-26" in head


def test_render_current_md_layer_status_section_non_empty(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    assert "## Layer status" in out
    # Each layer in layers.yaml appears as a `### {layer_id}` heading.
    assert re.search(r"^### L1\b", out, re.MULTILINE)
    assert re.search(r"^### L12\b", out, re.MULTILINE)
    # Non-empty interpretation lines under each layer block.
    layer_status_idx = out.index("## Layer status")
    # Use `\n## ` to anchor at start-of-line; otherwise "### L1" matches "## ".
    next_section = out.index("\n## ", layer_status_idx + 5)
    block = out[layer_status_idx:next_section]
    assert "all 1 scopes errored" in block or "no evidence emitted yet" in block
    assert "per-session summary; no snapshot evidence" in block


def test_render_current_md_recurring_reviews_section_non_empty(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    assert "## Recurring reviews" in out
    assert "calibration_audit" in out
    assert "escalation_review" in out


def test_render_current_md_parking_lot_is_link_not_copy(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    assert "docs/keel/checklist.md" in out
    # The known-unique parking-lot canary string from checklist.md must NOT
    # appear in CURRENT.md (proves we link, not duplicate).
    assert "KNOWN_PARKING_LOT_CANARY_LINE_xyzz" not in out


def test_render_current_md_open_questions_section_lists_headings(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    assert "docs/keel/open_questions.md" in out
    # Each `### N. Title` heading from open_questions.md must appear.
    assert "1. Evidence retention" in out
    assert "2. Evidence commit path and publication policy" in out
    assert "3. Human escalation budget" in out
    # Non-numbered headings (R1, the meta-question) should NOT be parsed in.
    # Implementation parses `^### \d+\. ` only.
    assert "R1. Layer numbering" not in out


def test_render_current_md_footer_names_regen_command(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    last_lines = out.rstrip().splitlines()[-3:]
    assert any("make keel-current" in line for line in last_lines)


def test_render_current_md_idempotent_under_unchanged_inputs(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    a = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    b = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    assert a == b


def test_render_current_md_changes_when_source_changes(tmp_path: Path) -> None:
    """Cache-bug detection: idempotency alone could pass for the wrong
    reason if the implementation cached results across calls. Mutating a
    source file between calls must produce different output."""
    repo = _build_synthetic_repo(tmp_path)
    before = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    # Add a new OQ heading to open_questions.md.
    oq_path = repo / "docs" / "keel" / "open_questions.md"
    oq_path.write_text(
        oq_path.read_text(encoding="utf-8") + "\n### 99. Brand new question\nbody.\n",
        encoding="utf-8",
    )
    after = keel_current.render_current_md(repo_root=repo, today_utc=date(2026, 4, 26))
    assert before != after
    assert "99. Brand new question" in after


def test_main_writes_default_path(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    rc = keel_current.main(["--repo-root", str(repo), "--date", "2026-04-26"])
    assert rc == 0
    out_path = repo / "docs" / "keel" / "CURRENT.md"
    assert out_path.is_file()
    content = out_path.read_text(encoding="utf-8")
    assert content.startswith("<!-- GENERATED by make keel-current")


def test_main_writes_to_explicit_out(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    out_path = tmp_path / "out.md"
    rc = keel_current.main(
        ["--repo-root", str(repo), "--date", "2026-04-26", "--out", str(out_path)]
    )
    assert rc == 0
    assert out_path.is_file()


def test_main_default_date_uses_utc_not_local_time(tmp_path: Path, monkeypatch) -> None:
    """Casual rollup must use the same UTC clock as `make keel-status` so
    the two never disagree on the same evidence's freshness when the
    operator's local TZ straddles UTC midnight.

    Defends against the regression we just fixed: `date.today()` uses
    local time and skews from `make keel-status`'s `datetime.now(UTC)`.

    Strategy: patch BOTH clocks to deterministic-but-DIFFERENT dates,
    then assert the UTC date wins. Patching only `datetime.now` would
    leave a TZ-dependent false-positive — on a UTC server, `date.today`
    happens to agree with UTC and a `date.today()`-based bad impl would
    also produce 2026-04-27, passing the test for the wrong reason.
    """
    repo = _build_synthetic_repo(tmp_path)
    utc_target_dt = datetime(2026, 4, 27, 0, 5, tzinfo=UTC)
    local_decoy_date = date(1999, 1, 1)  # known-wrong; far from any real run

    class _FrozenDateTime(datetime):
        @classmethod
        def now(cls, tz=None):  # type: ignore[override]
            return utc_target_dt

    class _FrozenDate(date):
        @classmethod
        def today(cls):  # type: ignore[override]
            return local_decoy_date

    monkeypatch.setattr(keel_current, "datetime", _FrozenDateTime)
    monkeypatch.setattr(keel_current, "date", _FrozenDate)
    rc = keel_current.main(["--repo-root", str(repo)])
    assert rc == 0
    out = (repo / "docs" / "keel" / "CURRENT.md").read_text(encoding="utf-8")
    assert "2026-04-27" in out, "casual rollup default date must come from UTC clock"
    assert "1999-01-01" not in out, "casual rollup must NOT pick up local-time date.today()"


def test_main_writer_idempotent_end_to_end(tmp_path: Path) -> None:
    repo = _build_synthetic_repo(tmp_path)
    keel_current.main(["--repo-root", str(repo), "--date", "2026-04-26"])
    a = (repo / "docs" / "keel" / "CURRENT.md").read_text(encoding="utf-8")
    keel_current.main(["--repo-root", str(repo), "--date", "2026-04-26"])
    b = (repo / "docs" / "keel" / "CURRENT.md").read_text(encoding="utf-8")
    assert a == b
