"""Pinned structured-rule seed matrix used by the checked-in config tests."""

from __future__ import annotations


RuleProjection = tuple[str | int | bool | None, ...]

RULE_PROJECTION_FIELDS = (
    "donor_type",
    "recipient_type",
    "office_level",
    "election_type",
    "limit_status",
    "limit_amount",
    "limit_basis",
    "local_override_allowed",
)

# The structured seed matrix seeded into the checked-in configs, per jurisdiction. CO/CA
# direct corporate and union flat-block channels are intentionally kept out of this
# bounded matrix and are pinned by out-of-matrix tests in the checked-in config test.
EXPECTED_STRUCTURED_RULE_COUNTS: dict[str, int] = {
    "cities-LA": 6,
    "cities-NYC": 9,
    "cities-PHL": 5,
    "cities-SF": 6,
    "states-CA": 12,
    "states-CO": 18,
    "states-GA": 30,
    "states-NC": 6,
}
EXPECTED_STRUCTURED_RULE_PROJECTIONS: dict[str, list[RuleProjection]] = {
    "cities-LA": [
        ("individual", "candidate_committee", "city_council", None, "numeric", 500, "per_election", False),
        ("individual", "candidate_committee", "citywide", None, "numeric", 1000, "per_election", False),
        ("pac", "candidate_committee", "city_council", None, "numeric", 500, "per_election", False),
        ("pac", "candidate_committee", "citywide", None, "numeric", 1000, "per_election", False),
        ("union", "candidate_committee", "city_council", None, "numeric", 500, "per_election", False),
        ("union", "candidate_committee", "citywide", None, "numeric", 1000, "per_election", False),
    ],
    "cities-NYC": [
        ("individual", "candidate_committee", "borough_president", None, "numeric", 1500, "per_election", False),
        ("individual", "candidate_committee", "city_council", None, "numeric", 1000, "per_election", False),
        ("individual", "candidate_committee", "citywide", None, "numeric", 2000, "per_election", False),
        ("pac", "candidate_committee", "borough_president", None, "numeric", 1500, "per_election", False),
        ("pac", "candidate_committee", "city_council", None, "numeric", 1000, "per_election", False),
        ("pac", "candidate_committee", "citywide", None, "numeric", 2000, "per_election", False),
        ("union", "candidate_committee", "borough_president", None, "numeric", 1500, "per_election", False),
        ("union", "candidate_committee", "city_council", None, "numeric", 1000, "per_election", False),
        ("union", "candidate_committee", "citywide", None, "numeric", 2000, "per_election", False),
    ],
    "cities-PHL": [
        ("corporation", "candidate_committee", None, None, "unknown", None, None, False),
        ("individual", "candidate_committee", None, None, "unknown", None, None, False),
        ("pac", "candidate_committee", None, None, "unknown", None, None, False),
        ("party_committee", "candidate_committee", None, None, "unknown", None, None, False),
        ("union", "candidate_committee", None, None, "unknown", None, None, False),
    ],
    "cities-SF": [
        ("individual", "candidate_committee", "board_of_supervisors", None, "numeric", 500, "per_election", False),
        ("individual", "candidate_committee", "citywide", None, "numeric", 500, "per_election", False),
        ("pac", "candidate_committee", "board_of_supervisors", None, "numeric", 500, "per_election", False),
        ("pac", "candidate_committee", "citywide", None, "numeric", 500, "per_election", False),
        ("union", "candidate_committee", "board_of_supervisors", None, "numeric", 500, "per_election", False),
        ("union", "candidate_committee", "citywide", None, "numeric", 500, "per_election", False),
    ],
    "states-CA": [
        ("individual", "candidate_committee", "legislative", None, "numeric", 5900, "per_election", False),
        (
            "individual",
            "candidate_committee",
            "statewide_except_governor",
            None,
            "numeric",
            9800,
            "per_election",
            False,
        ),
        ("individual", "candidate_committee", "governor", None, "numeric", 39200, "per_election", False),
        ("pac", "candidate_committee", "legislative", None, "numeric", 5900, "per_election", False),
        (
            "pac",
            "candidate_committee",
            "statewide_except_governor",
            None,
            "numeric",
            9800,
            "per_election",
            False,
        ),
        ("pac", "candidate_committee", "governor", None, "numeric", 39200, "per_election", False),
        (
            "small_contributor_committee",
            "candidate_committee",
            "legislative",
            None,
            "numeric",
            11800,
            "per_election",
            False,
        ),
        (
            "small_contributor_committee",
            "candidate_committee",
            "statewide_except_governor",
            None,
            "numeric",
            19600,
            "per_election",
            False,
        ),
        (
            "small_contributor_committee",
            "candidate_committee",
            "governor",
            None,
            "numeric",
            39200,
            "per_election",
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "legislative",
            None,
            "no_statutory_limit",
            None,
            None,
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "statewide_except_governor",
            None,
            "no_statutory_limit",
            None,
            None,
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "governor",
            None,
            "no_statutory_limit",
            None,
            None,
            False,
        ),
    ],
    "states-CO": [
        ("individual", "candidate_committee", "statewide", None, "numeric", 725, "per_cycle", False),
        ("pac", "candidate_committee", "statewide", None, "numeric", 725, "per_cycle", False),
        ("individual", "candidate_committee", "legislative", None, "numeric", 225, "per_cycle", False),
        ("pac", "candidate_committee", "legislative", None, "numeric", 225, "per_cycle", False),
        ("individual", "candidate_committee", "county", None, "numeric", 1425, "per_cycle", True),
        ("pac", "candidate_committee", "county", None, "numeric", 1425, "per_cycle", True),
        ("individual", "candidate_committee", "municipal", None, "numeric", 400, "per_election", True),
        ("pac", "candidate_committee", "municipal", None, "numeric", 400, "per_election", True),
        (
            "individual",
            "candidate_committee",
            "school_district",
            None,
            "numeric",
            2500,
            "per_election",
            False,
        ),
        (
            "small_donor_committee",
            "candidate_committee",
            "statewide",
            None,
            "numeric",
            7825,
            "per_cycle",
            False,
        ),
        (
            "small_donor_committee",
            "candidate_committee",
            "legislative",
            None,
            "numeric",
            3100,
            "per_cycle",
            False,
        ),
        (
            "small_donor_committee",
            "candidate_committee",
            "county",
            None,
            "numeric",
            14400,
            "per_cycle",
            True,
        ),
        (
            "small_donor_committee",
            "candidate_committee",
            "school_district",
            None,
            "numeric",
            25000,
            "per_election",
            False,
        ),
        ("party_committee", "candidate_committee", "governor", None, "numeric", 789060, "per_cycle", False),
        (
            "party_committee",
            "candidate_committee",
            "statewide_except_governor",
            None,
            "numeric",
            157805,
            "per_cycle",
            False,
        ),
        ("party_committee", "candidate_committee", "legislative", None, "numeric", 20500, "per_cycle", False),
        ("individual", "party_committee", None, None, "numeric", 4675, "per_calendar_year", False),
        ("small_donor_committee", "party_committee", None, None, "numeric", 23600, "per_calendar_year", False),
    ],
    "states-GA": [
        ("individual", "candidate_committee", "statewide", "primary", "numeric", 8400, "per_election", False),
        ("individual", "candidate_committee", "statewide", "general", "numeric", 8400, "per_election", False),
        ("individual", "candidate_committee", "statewide", "runoff", "numeric", 4800, "per_election", False),
        ("individual", "candidate_committee", "other_office", "primary", "numeric", 3300, "per_election", False),
        ("individual", "candidate_committee", "other_office", "general", "numeric", 3300, "per_election", False),
        ("individual", "candidate_committee", "other_office", "runoff", "numeric", 1800, "per_election", False),
        ("pac", "candidate_committee", "statewide", "primary", "numeric", 8400, "per_election", False),
        ("pac", "candidate_committee", "statewide", "general", "numeric", 8400, "per_election", False),
        ("pac", "candidate_committee", "statewide", "runoff", "numeric", 4800, "per_election", False),
        ("pac", "candidate_committee", "other_office", "primary", "numeric", 3300, "per_election", False),
        ("pac", "candidate_committee", "other_office", "general", "numeric", 3300, "per_election", False),
        ("pac", "candidate_committee", "other_office", "runoff", "numeric", 1800, "per_election", False),
        ("corporation", "candidate_committee", "statewide", "primary", "numeric", 8400, "per_election", False),
        ("corporation", "candidate_committee", "statewide", "general", "numeric", 8400, "per_election", False),
        ("corporation", "candidate_committee", "statewide", "runoff", "numeric", 4800, "per_election", False),
        (
            "corporation",
            "candidate_committee",
            "other_office",
            "primary",
            "numeric",
            3300,
            "per_election",
            False,
        ),
        (
            "corporation",
            "candidate_committee",
            "other_office",
            "general",
            "numeric",
            3300,
            "per_election",
            False,
        ),
        (
            "corporation",
            "candidate_committee",
            "other_office",
            "runoff",
            "numeric",
            1800,
            "per_election",
            False,
        ),
        ("union", "candidate_committee", "statewide", "primary", "numeric", 8400, "per_election", False),
        ("union", "candidate_committee", "statewide", "general", "numeric", 8400, "per_election", False),
        ("union", "candidate_committee", "statewide", "runoff", "numeric", 4800, "per_election", False),
        ("union", "candidate_committee", "other_office", "primary", "numeric", 3300, "per_election", False),
        ("union", "candidate_committee", "other_office", "general", "numeric", 3300, "per_election", False),
        ("union", "candidate_committee", "other_office", "runoff", "numeric", 1800, "per_election", False),
        (
            "party_committee",
            "candidate_committee",
            "statewide",
            "primary",
            "numeric",
            8400,
            "per_election",
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "statewide",
            "general",
            "numeric",
            8400,
            "per_election",
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "statewide",
            "runoff",
            "numeric",
            4800,
            "per_election",
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "other_office",
            "primary",
            "numeric",
            3300,
            "per_election",
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "other_office",
            "general",
            "numeric",
            3300,
            "per_election",
            False,
        ),
        (
            "party_committee",
            "candidate_committee",
            "other_office",
            "runoff",
            "numeric",
            1800,
            "per_election",
            False,
        ),
    ],
    "states-NC": [
        ("individual", "candidate_committee", None, None, "numeric", 6800, "per_election", False),
        ("pac", "candidate_committee", None, None, "numeric", 6800, "per_election", False),
        ("party_committee", "candidate_committee", None, None, "unlimited", None, None, False),
        ("self", "candidate_committee", None, None, "unlimited", None, None, False),
        ("corporation", "candidate_committee", None, None, "prohibited", None, None, False),
        ("union", "candidate_committee", None, None, "prohibited", None, None, False),
    ],
}

CA_FLAT_BLOCK_VINTAGE_LIMITS = {
    "individual_to_candidate": 5500,
    "pac_to_candidate": 10200,
    "corporate_direct": "prohibited",
    "union_direct": "prohibited",
}
CA_STRUCTURED_2025_26_CANDIDATE_LIMITS = {
    ("individual", "legislative"): 5900,
    ("individual", "statewide_except_governor"): 9800,
    ("individual", "governor"): 39200,
    ("pac", "legislative"): 5900,
    ("pac", "statewide_except_governor"): 9800,
    ("pac", "governor"): 39200,
    ("small_contributor_committee", "legislative"): 11800,
    ("small_contributor_committee", "statewide_except_governor"): 19600,
    ("small_contributor_committee", "governor"): 39200,
}
CO_LOCAL_OVERRIDE_OFFICE_LEVELS = ("county", "municipal")
